### PR TITLE
Move comon code from isodoc/*_convert.rb to isodoc/base_convert.rb

### PR DESCRIPTION
**Pull request by CAMOBAP795**
- https://github.com/metanorma/metanorma-iso/issues/267
 - https://github.com/metanorma/metanorma-build-scripts/issues/3

### CODE REVIEW

**Comment by opoudjis** [comment]
@CAMOBAP795 You will have to remove ruby/xslt from https://raw.githubusercontent.com/metanorma/metanorma-build-scripts/master/appveyor.ps1

**Comment by CAMOBAP795** [comment]
@opoudjis I think still no because `ruby-xslt` still contains in `Gemfile.lock`  for several modules, and looks like we need to release at least:
 - metanorma-standoc
 - metanorma-cli
 - metanorma-csand

IDK maybe another too

**Comment by opoudjis** [comment]
Ah. I had not released those gems last time, because there was no functionality change. I will release csand and m3d now; cli should then update automatically.

**Comment by opoudjis** [comment]
Released metanorma-csand, metanorma-m3d

**Pull request merged**
